### ISSUE TITLE
HIDPI support

### ISSUE THREAD

**Issue by TatriX** [geontime/geonkick#16]
Is it possible to scale interface somehow? It's too small on 4K screen. Thanks!

**Comment by iurienistor** [comment]
Hi! Thank for the suggestion, I'll see what I can do. Geonkick depends of Redkite GUI toolkit where I need to implement this support.

**Comment by iurienistor** [comment]
I have create an issue for Redkite related to this https://github.com/geontime/redkite/issues/13
The current one I'll close since is not directly relate to Geonkick. Think you! ;)

**Comment by iurienistor** [comment]
Implemented here: https://github.com/iurie-sw/geonkick/issues/16

**Comment by iurienistor** [comment]
https://github.com/iurie-sw/geonkick/issues/80
