### ISSUE TITLE
Build error rkpng2c command not found

### ISSUE THREAD

**Issue by AS383** [geontime/geonkick#17]
I try to build version 1.9.2 from source and get an error:
[  0%] Generating resources/about_png.c
/bin/sh: rkpng2c: command not found
make[2]: *** [CMakeFiles/gkick_resources.dir/build.make:185: resources/about_png.c] Error 127
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/gkick_resources.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

All dependencies are installed. I find a similar tool https://github.com/apre/png2c Is it compatible?

**Comment by iurienistor** [comment]
It seems that you haven't built and installed Redkite GUI toolkit. - https://github.com/geontime/redkite

**Comment by AS383** [comment]
@iurienistor Thanks. But GUI Toolkit configures with error [CXX_STANDARD is set to invalid value 17](https://github.com/geontime/redkite/issues/14).
