### ISSUE TITLE
Add envelope to the distortion drive

### ISSUE THREAD

**Issue by Ogami-Z** [geontime/geonkick#19]
This is a great well laid out & intuitive drum synth. But since I use the linux version of reaper which doesn't support lv2 it would be great to have a linux vst version. I'm currently using this plugin via the bridging lv2vst plugin which allows some but not all lv2 plugins to be seen as a vst, but it can be a bit buggy at times causing crashes.

Also might I suggest some added modulation sources & destinations like kick drive or filters etc. being modulated by an envelope.

**Comment by iurienistor** [comment]
Hi, thank you :) VST3 for GNU/Linux is being developed on the branch https://github.com/geontime/geonkick/tree/feat/vst3_gnu  but for now is stopped and I'll continue to work on it after I'll release and important feature (geonKIT) under the version 1.10. 

All filters have envelops for cutoff frequency. See the button "cutoff". But as far as I understand you mean to modulate all this only by a single envelope, i.e. to route one envelope to these parameters like drive, filter cuttoff, etc?

**Comment by Ogami-Z** [comment]
Looking forward to geonKIT & the linux vst3 version. Yes I meant routing modulation to different sources, not a necessity but a nice feature to have.

**Comment by iurienistor** [comment]
@Ogami-Z I think there is good idea to add envelope for distortion drive. Thus, this till be implemented in 2.0.

**Comment by iurienistor** [comment]
Implemented. release branch/v.10
