### ISSUE TITLE
Feature request: random seed parameter

### ISSUE THREAD

**Issue by magnetophon** [geontime/geonkick#37]
Thanks for Geonkick, I love it!

At the moment the noise seems to be recalculated whenever you change any parameter, no matter if it's noise related, or even in the same layer.
This is very noticeable when you have a patch with an osc and an oscillating filter at similar frequencies and levels: they amplify or cancel out differently at every tweak.

It would be great if the noise would be deterministic, so you could better hone in on a sound.
At the same time it would be a shame to lose al the different variations in sound.
 A random seed parameter for each noise source would give you both.

**Comment by iurienistor** [comment]
Hi, interesting idea! I'll think how to implement this. I'll try to develop this for v2.0.

For now, at the same time you if want to have a static noise, OSC1 and OSC2 can load samples, thus, you can load a sample noise and use is instead of static noise generator.

**Comment by magnetophon** [comment]
Cool, thanks!

**Comment by iurienistor** [comment]
@magnetophon

Implemented. Now the noise has a seed for noise generator. The control will change the seed from 0 to 1000, with a step of 10, thus, there will be 100 noise patterns. Saving and loading from preset, the noise pattern will not change. Thank you for this good idea. :)

The feature is in master, and will be available in 2.0 release. You can use it  now by compiling from master.

**Comment by iurienistor** [comment]
I think... i have missundertood the idea... ok, there is need just for a button to regenerate a new random seed.

**Comment by magnetophon** [comment]
No, I think you got it right: the idea is to always play the same noise when as long as the seed knobis at the same value, and play a different one when you change it.
When you go back to the first seed, use the first noise again.

Is that what you have?

I'll go compile now.  :)

**Comment by magnetophon** [comment]
It's perfect! Thank you!

**Comment by iurienistor** [comment]
good,  thank you :)
