### ISSUE TITLE
geonkick grabs all keys until the first click

### ISSUE THREAD

**Issue by magnetophon** [geontime/geonkick#43]
When I first start geonkick, either the standalone and the lv2, it grabs all keys, so I can't use my window manager anymore, until the first time I click somewhere, either on geonkick or elsewhere.

**Comment by iurienistor** [comment]
Geonkick acutally is not grabbing any keys... I don't see how it can affect window manager. What it  dose is notifying Geonkick main window that one if its child received input key. Can you check of this is happening before I have introduced the "k" commit?

**Comment by magnetophon** [comment]
I'm on NixOS with i3.
I'll try the older commit.

**Comment by iurienistor** [comment]
I can't reproduce this on Ubuntu/MATE I am using. Be sure if other applications is not grabbing the keys. If it will happen due to Geonkick, I'll check on other distros  and install NixOS with i3 is this is possible.

**Comment by magnetophon** [comment]
That's very generous of you.

Installing NixOS takes a bit of manual work, but you can also download a fully working [VirtualBox image](https://channels.nixos.org/nixos-19.09/latest-nixos-x86_64-linux.ova)

Then go into ``/etc/configuration.nix`` and change:
``desktopManager.plasma5.enable = true;`` to ``desktopManager.plasma5.enable = false;``
 add ``windowManager.i3.enable = true;`` and remove the other wm, not sure what it's called.

To apply your changes, run ``nixos-rebuild switch`` as root, and of course log out and back in.

Lemme know how it goes.

**Comment by iurienistor** [comment]
Ok, thank you, I am downloading the image :)

**Comment by magnetophon** [comment]
1.10.0 also does it.

**Comment by iurienistor** [comment]
Also, please, can you describe  what do you mean you can't use window manager... you can't use shortcuts from window manager?

**Comment by magnetophon** [comment]
Yes.

**Comment by iurienistor** [comment]
Ok, thank you. I have downloaded the ISO because VM file is not working. I'll create an VM machine to test.

**Comment by magnetophon** [comment]
Thanks.  I warned you about the install though!
It's not that bad, just some manual work: https://nixos.org/nixos/manual/index.html#sec-installation-installing

**Comment by magnetophon** [comment]
What did the VM do/not do?

**Comment by magnetophon** [comment]
BTW, have you tried it with i3 on a box/VM that's already installed?
I mean, it'd be great if you installed nixos and liked it, so we'd have another talented dev on board ``the best OS in the world™``  ;) , but the truth is NixOS is not everybody's cup of tea.

**Comment by iurienistor** [comment]
I meant I couldn't start VM *.ova, VirtualBox gives me an error. I'll install it from ISO... actually I can install i3 on Ubuntu and start testing from because. If I am not wrong NixOS  is using X11 too. So, the problem may be due to i3 window manager.

**Comment by magnetophon** [comment]
Yup, regular X11,unless you set it to use wayland, which I haven't.

**Comment by iurienistor** [comment]
They only way I can reproduce is to restart the OS (even on Ubuntu) several times until I can catch it.  If fist time Geonkick is started and click is done on it or somewhere... keys are working ok.... If OS is not restarted than after click... even is the program is restarted... it will not reproduce anymore. It might be related to X11. I'll try in KDE if I can reproduce.

**Comment by magnetophon** [comment]
For me the problem is only when I *don't* click.

**Comment by iurienistor** [comment]
Hi, it seems that I have fixed the issue. Please, try now the latest changes from the master, it should not reproduce the issue. Please, confirm if it is ok.

**Comment by magnetophon** [comment]
Yup, that fixes it, thanks!
Now I'm curious: how did you reproduce, and what was the bug?

**Comment by iurienistor** [comment]
Before running the Geonkick, first focus on a window. After the start of Geonkick, Geonkick main window was losing focus because I set unnecessarily manually focus to false for all buttons. Due to this X11 is not managing correctly to refocus on the last focused window, thus, window manager (no matter which) lost the focus too. To recover you'd have ether to click on Geonkick window, or any other window in order window manager to regain focus. I think this scenario should not happen, this may be an X11 issue, maybe due to the synchronization with the X11 server.

I am glad it fixed. Thank you for reporting this.

**Comment by magnetophon** [comment]
So in the end you could reproduce it in any WM? Even your own install?

**Comment by iurienistor** [comment]
Yes. Ubuntu/MATE, Linux Mint/GNOME, Fedora/GNOME
