### ISSUE TITLE
it is generation mono sounds ,not stereo also some high pitch sound at 737.2hz?

### ISSUE THREAD

**Issue by nahush2321** [geontime/geonkick#45]
i have been using this for few months ,but after the current update , it actually started to soug only in mono .i did try other option from Ardour but only stereo image helps to make sense.i think it might be something bugging. please do let me know if anything i can help with.also notice a constant soung which arises at 737.2hz of 14 db value. please check this also.the sound is constant and it cannot be removed by the application LP filter as well, we need to use the external filter application for that to go

My terminal output of ardour ,while geonkick is working
`[musicarch@Narch-Music ~]$ ardour5
bind txt domain [gtk2_ardour5] to /usr/share/ardour5/locale
Ardour5.12.0 (built using 5.12 and GCC version 9.2.1 20200130)
ardour: [INFO]: Your system is configured to limit Ardour to only 524288 open files
ardour: [INFO]: Loading system configuration file /etc/ardour5/system_config
ardour: [INFO]: Loading user configuration file /home/musicarch/.config/ardour5/config
ardour: [INFO]: CPU vendor: GenuineIntel
ardour: [INFO]: AVX-capable processor
ardour: [INFO]: CPU brand:       Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz
ardour: [INFO]: Using SSE optimized routines
ardour: [INFO]: Loading default ui configuration file /etc/ardour5/default_ui_config
ardour: [INFO]: Loading user ui configuration file /home/musicarch/.config/ardour5/ui_config

(process:4682): Gtk-WARNING **: 12:06:30.745: Locale not supported by C library.
	Using the fallback 'C' locale.
Color shuttle bg not found
ardour: [INFO]: Loading color file /usr/share/ardour5/themes/dark-ardour.colors
ardour: [INFO]: Loading ui configuration file /etc/ardour5/clearlooks.rc
ardour: [INFO]: Loading ui configuration file /etc/ardour5/clearlooks.rc
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Found 1 along /home/musicarch/.config/ardour5/templates:/usr/share/ardour5/templates
run dialog
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JACK command line will be: /usr/bin/jackd -t 200 -p 2048 -R -T -d alsa -n 2 -r 44100 -p 1024 -d hw:PCH,0 -X raw
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.14
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2019 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Could not open component .so '/usr/lib/jack/jack_firewire.so': libffado.so.2: cannot open shared object file: No such file or directory
Could not open component .so '/usr/lib/jack/jack_firewire.so': libffado.so.2: cannot open shared object file: No such file or directory
jack_get_descriptor : dll jack_firewire.so is not a driver
jack_get_descriptor returns null for 'jack_firewire.so'
Could not open component .so '/usr/lib/jack/jack_firewire.so': libffado.so.2: cannot open shared object file: No such file or directory
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:PCH,0|hw:PCH,0|1024|2|44100|0|0|nomon|swmeter|-|32bit
configuring for 44100Hz, period = 1024 frames (23.2 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_tyu.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_tyu.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_tyu.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_Chors1.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_Chors1.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_Chors1.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_tryty4.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_tryty4.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_tryty4.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_Chords_1.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_Chords_1.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_Chords_1.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_try_2.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_try_2.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_try_2.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_chords4.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_chords4.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_chords4.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_uiu.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_uiu.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_uiu.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_Chords_2.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_Chords_2.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_Chords_2.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_yui.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_yui.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_yui.lv2/manifest.ttl
Scanning folders for bundled LV2s: /usr/lib/ardour5/LV2
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_tyu.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_tyu.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_tyu.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_Chors1.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_Chors1.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_Chors1.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_tryty4.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_tryty4.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_tryty4.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_Chords_1.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_Chords_1.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_Chords_1.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_try_2.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_try_2.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_try_2.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_chords4.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_chords4.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_chords4.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_uiu.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_uiu.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_uiu.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_Chords_2.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_Chords_2.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_Chords_2.lv2/manifest.ttl
error: failed to open file /home/musicarch/.lv2/ZynAddSubFX_yui.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/musicarch/.lv2/ZynAddSubFX_yui.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/musicarch/.lv2/ZynAddSubFX_yui.lv2/manifest.ttl
Set cursor set to default
JackGraphManager::Connect already connected port_src = 9 port_dst = 3
JackGraphManager::Connect already connected port_src = 10 port_dst = 4
JackGraphManager::Connect already connected port_src = 1 port_dst = 7
JackGraphManager::Connect already connected port_src = 25 port_dst = 3
JackGraphManager::Connect already connected port_src = 26 port_dst = 4
actually writing state to /home/musicarch/Music/Ardour sessions/geonm/geonm.tmp
renaming state to /home/musicarch/Music/Ardour sessions/geonm/geonm.ardour
actually writing state to /home/musicarch/Music/Ardour sessions/geonm/geonm.tmp
renaming state to /home/musicarch/Music/Ardour sessions/geonm/geonm.ardour
actually writing state to /home/musicarch/Music/Ardour sessions/geonm/geonm.tmp
renaming state to /home/musicarch/Music/Ardour sessions/geonm/geonm.ardour
actually writing state to /home/musicarch/Music/Ardour sessions/geonm/geonm.tmp
renaming state to /home/musicarch/Music/Ardour sessions/geonm/geonm.pendin `

**Comment by iurienistor** [comment]
Hi, thank you for using Geonkick!  Geonkick is mono (before and now too). Before the mono sound was just replicated for two output channels. Now Geonkick supports up to 16 audio output channels for LV2 and just one channel for standalone version, and every percussion from the kit list ([see the Documentation](https://github.com/geontime/geonkick/wiki/Geonkick-Documentation)) can be sent to one of the channel.

> "soung which arises at 737.2hz of 14 db value. please check this also.the sound is constant and it cannot be removed by the application LP filter as well"

I don't really understand what do you mean by this. But if you are using the "Tune" option, for keys higher then A4 the sound may contain additional frequencies for some kind of sounds ([see the Documentation](https://github.com/geontime/geonkick/wiki/Geonkick-Documentation) about "Tune") . Geonkick when tuning does not apply any antialiasing filters.

**Comment by nahush2321** [comment]
> I don't really understand what do you mean by this. But if you are using the "Tune" option, for keys higher then A4 the sound may contain additional frequencies for some kind of sounds (see the Documentation about "Tune") . Geonkick when tuning does not apply any antialiasing filters.

i am asking about the high pitch frequency sound which is there  as soon as the lv2 version starts . nothing about the tune .just only the default plugin.

thank you

**Comment by iurienistor** [comment]
I can't reproduce this in Ardour 5.12. I hardly imagine how this may happen for Geonkick. Geonkick can't generate continuous lasting sounds. I think this sound comes from another source. Please, can you make a video with a default session, with no other tracks and plugins than Geonkick and reproduce the issue?

**Comment by iurienistor** [comment]
It is interesting that your Adrour instance is even not connected Jack server, I don't know how it can even reproduce sound. 

> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel

**Comment by nahush2321** [comment]
> I can't reproduce this in Ardour 5.12. I hardly imagine how this may happen for Geonkick. Geonkick can't generate continuous lasting sounds. I think this sound comes from another source. Please, can you make a video with a default session, with no other tracks and plugins than Geonkick and reproduce the issue.
      
              it was mistake on my part not on the software , i am sorry for causing u inconviniance
