### ISSUE TITLE
double clicking and dragging should start a node drag action

### ISSUE THREAD

**Issue by alex-tee** [geontime/geonkick#5]
right now you have to first double click to create a node, and then you have to release the mouse button and click again to drag it. i would expect double clicking and dragging in one go to work.

also, would be nice if the hovered nodes were highlighted for better visibility of what's going on

**Comment by iurienistor** [comment]
Hi! Thank you these very good ideas. :) I have scheduled them for version 1.10.

**Comment by iurienistor** [comment]
Implemented, both features. Now they are in master. Thank you!
