### ISSUE TITLE
How to use individual audio outputs in the LV2 plug-in?

### ISSUE THREAD

**Issue by unfa** [geontime/geonkick#54]
I guess Geonkick would need a 16-output version or something, as LV2 doesn't allow dynamically changing port configuration, right?

![image](https://user-images.githubusercontent.com/491704/79215390-b60a5980-7e4b-11ea-9dfe-4ef4fe4f7aed.png)

How do I use multiple audio outputs in Ardour?

**Comment by iurienistor** [comment]
![touput7](https://user-images.githubusercontent.com/56111777/79216346-aee84900-7e55-11ea-97c4-8dc20ad9d4cc.png)

Probably your Geonkick plugin haven't been updated correctly (probably *.tt files form the plugin were not updated). It should have 16 output audio channels.

**Comment by unfa** [comment]
FTR: I have forgot to restart Ardour after updating Geonkick. Re-scanning the plug-ins is not enough to fully update what Ardour knows about plug-ins.

Maybe I should report this to Ardour developers.

Not a bug in Geonkick.
