### ISSUE TITLE
Allow reordering Kit channels

### ISSUE THREAD

**Issue by unfa** [geontime/geonkick#55]
Say I have made my kit wit ha Kick.Snare and HiHat, but then I decided to add an alternate snare:

![image](https://user-images.githubusercontent.com/491704/79215699-4183ea80-7e4c-11ea-83b3-2a2a6a0f59de.png)

Is there a way to reorder the items, so my two snares are grouped together?

**Comment by iurienistor** [comment]
Up/Down - to navigate into the kit list
Ctrl + Up/Down - to move up/down the position of the current selected percussion from the kit list
https://github.com/geontime/geonkick/blob/master/doc/Documentation.md#shortcut-keys

**Comment by unfa** [comment]
Fantastic, thank you!

**Comment by unfa** [comment]
I think some GUI hint or button would be nice for this function.
I totally forgot it's even there.

Maybe some Up/Down buttons that move the selected kit element?

**Comment by iurienistor** [comment]
"Maybe some Up/Down buttons that move the selected kit element?", yes, it would be nice, but there are also buttons for "play", "copy", "remove", "solo", "mute"... and I afraid this will overload the UI. I'll think how I can add this...
