### ISSUE TITLE
Output channels are offset by 1?

### ISSUE THREAD

**Issue by unfa** [geontime/geonkick#59]
I've tried using the audio output channel settings:

![Screenshot_20200414_124557](https://user-images.githubusercontent.com/491704/79216678-e521ca80-7e4d-11ea-9a6b-4efd0163d695.png)

It sounds on my system like the output #0 plays sound in the right ear, while all others are inaudible (with 2 channel output from the plug-in):

![Screenshot_20200414_124644](https://user-images.githubusercontent.com/491704/79216755-02569900-7e4e-11ea-8284-a11b7f7e89c5.png)

I'd expect channel #0 to play in left ear, and channel #1 to play in the right ear.

**Comment by iurienistor** [comment]
0-15 channels will got to 1-16 channels in Ardour. Geonkick should be have here with 16 channels output not only two. See if Geonkick plugin was updated correctly.

**Comment by unfa** [comment]
You must be right. I think I'll have to restart Ardour (didn't do that) - it's probably using old TTL file with the new binary...

**Comment by unfa** [comment]
Yes, that was my fault.
