### ISSUE TITLE
lv2 instance-access not specified in UI required features

### ISSUE THREAD

**Issue by falkTX** [geontime/geonkick#6]
Without this, hosts like carla will try to run the UI in a separate process (for safety).
But geonkick does not support this, so the ui just segfaults without having instance-access pointer.

Would be nice if the plugin did not need such a feature.
But for now, please add
```
lv2:requiredFeature <http://lv2plug.in/ns/ext/instance-access> ;
```
to the UI ttl stuff.

**Comment by iurienistor** [comment]
@falkTX  Hi! Thank you for rising this issue. The fix now is committed in master and will be available as a part of Version 1.10.
