### ISSUE TITLE
Idea: GeonKIT

### ISSUE THREAD

**Issue by unfa** [geontime/geonkick#7]
I think I've found a perfect name for a multitimbral version of Geonkick:

GeonKIT

**Comment by iurienistor** [comment]
@unfa Ah, you know... it's an interesting idea :)... I'll think about it how it might be implemented. As far as I understand you want for different pitch, different preset, mapping keys to presets.

**Comment by unfa** [comment]
Yes, I'd imagine something like a trigger 4x4 grid, where the user can assign a MIDI note to each pad and have a different Geonkick patch played for it.

The user interface could be exactly like the current one except with a n additional panel to the right for example , with the trigger grid, MIDI settigs. Clicking on a pad would hilight it and bring it's patch up to the main UI for editing. Labeling the patches with custom names and copy/paste for patches between slots would be cool extra features.

16-channel audio output would be sure useful for mixing the patches afterwards. I would definitely want to use such a plug-in for live performances or production. I tend to do all my drums with Geonkick nowadays, it just beats everything else when it comes to precision, ease of tuning and consistency between hits.

No pressure though - the idea came from the name.

**Comment by iurienistor** [comment]
@unfa Thank you for the idea. I think is a good one and I'll implement it.

**Comment by iurienistor** [comment]
Update: I think I've made a significat progress into this to a point where the kit can be loaded and played with its own midi key. Can be loaded up to 16 percussions. Now remained less important this like saving this, and adding new ones, add some additional things, and refining. I hope soon to release this feature.
![kit](https://user-images.githubusercontent.com/56111777/75623392-359cdb80-5bb2-11ea-8f18-ed95c09fb92c.png)

**Comment by unfa** [comment]
Awesome!

**Comment by iurienistor** [comment]
Implemented. Now is in release/v1.10 branch. Release 1.10 I think will be published soon after some other small features, polishing and testing. Version 1.10 will ot be compatible with older versions regarding LV2 save/load state.

**Comment by unfa** [comment]
Fantastic! I can't wait to test this out!

**Comment by iurienistor** [comment]
@unfa Here is a video where I demonstrate the geonkit feature https://www.youtube.com/watch?v=72QDwjE6DqI

The feature is in the master. In order to build, first build and install Redkite from the master.
