### ISSUE TITLE
The 'K' key doesn't trigger the sound any more

### ISSUE THREAD

**Issue by unfa** [geontime/geonkick#8]
I've just upgraded to 1.9, and it seems that a previously available hotkey 'K' for playing the current patch is no longer active.

I wish it was, because that makes it easier to listen to what I'm doing, without the need to use a MIDI keyboard.

I've tried other keys to no avail - was this feature removed?

**Comment by iurienistor** [comment]
I thought none was using it and it was against real-time rules. I'll bring it back. :)

**Comment by unfa** [comment]
Thanks!

**Comment by iurienistor** [comment]
Done. No it is in the master. Will be released in Version 1.10. Thank you!
